### ISSUE TITLE
구체적인 주제선정

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#1]
우리는 이번에 검출과 분류 기능을 가진 프로젝트를 만들어야 한다.
그래서 우리의 주제로 
인바디검사를 통한 신체정보를 파악(검출)
파악한 정보를 사용자에게 필요한 운동이나 기호에 맞는 운동을 추천(분류)
이라는 틀로 잡았다.
세부적으로 들어가서 이러한 데이터를 어떻게 쓸 것이며, 운동을 정보를 토대로 어떻게 추천할지에 대해 고민해보고
추가되었으면 하는 기능이 있다면 말해보자

**Comment by juhojang** [comment]
사용자의 운동이 필요한 부분은
사용자의 임바디 정보와 정상인의 임바디 정보의 비교를 통해
파악하도록 하자

**Comment by junhoprog** [comment]
다른 운동앱과 차별성을 줄 수 있게 운동을 함으로써 얻게되는 성취감을 극대화시켜주기 위해 출석체크식으로 체크하면서 하루하루 늘어가는 운동일과 횟수, 변화량을 기록하면서 사용자의 변화된 모습을 보여줄 수 있으면 좋겠어.

**Comment by JungHyeono** [comment]
인바디 정보에 체지방량, 골격근량이 나오니 체지방량이 많으면 유산소 운동쪽 추천하고 둘 다 부족하면 골격근량을 높이는 운동을 추천하게 하는게 좋을거 같습니다.
