### ISSUE TITLE
사용자 데이터 분석 함수의 구조에 대한 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#10]
사용자에게 받은 데이터를 어떻게 분석하여 그에 맞는 운동을 추천할 지 논의해봅시다.

일단, 저희가 받는 데이터는 다음과 같습니다.
1. 사용자의 성별
2. 사용자의 키
3. 사용자의 몸무게
4. 사용자의 체지방량
5. 사용자의 양팔 근육 백분율
6. 사용자의 양다리 근육 백분율
7. 사용자의 몸통근육 백분율

**Comment by junhoprog** [comment]
성별이나 키, 몸무게등에 따라 사용자의 기준이 달라지기 때문에 인바디에서 데이터를 분석하는 방법을 저희가 공부해서 상태를 파악하고
또, 근육과 체지방은 사용자의 이상적인 몸에 따라 기준이 달라지기 때문에 좀 더 세밀하게 기준을 정할 필요가 있는 것 같습니다.

**Comment by JungHyeono** [comment]
성별에 따라 키, 몸무게 기준이 나눠지고 거기에서 인바디 데이터의 표준모형을 잡아야 할 것 같습니다. 
그리고 체지방량, 골격근량은 저희가 발표한 그래프에서 강인형을 토대로 여러가지 데이터를 수집해야 할거 같습니다.
