### ISSUE TITLE
시작페이지 Radio 위젯(성별선택 위젯) 오류

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#11]
body:Center(
          child:Column(
              children:<Widget>[

              ListTile(
                title:Text('남자'),
                leading: Radio(
                  value:Gender.Man,
                  groupValue: _gender,
                  onChanged:(value){
                    setState(()
                    {
                      **__gender=value;_**
                    });
                  },
                ),
              ),
리스트 타일에서 Radio 위젯을 보면 **__gender=valued_**에서 에러가 뜹니다. Radio 프로퍼티 'value'와 변수 'value'에 대한 수정이 필요합니다.

**Comment by junhoprog** [comment]
해결 완료하였습니다!
