### ISSUE TITLE
텍스트 입력시 데이터 저장

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#13]
데이터를 입력할 경우 string, int로 입력받을 때가 있는데 각 경우에 따라 입력받는 함수가 다른건지 저장하는데 있어서 오류가 자꾸 떴습니다.
이에 대해 아는 내용 있으시다면 알려주시면 감사하겠습니다.

**Comment by JungHyeono** [comment]
어떤 오류가 뜨는지 이미지를 첨부해주실 수 있나요?

**Comment by juhojang** [comment]
다트언어는 자체적으로 변수 추정기능이 있기 때문에 그럴 때는 var타입으로 변수를 선언해서 입력받는게 어떨까요? 자동적으로 숫자를 입력하면 int형으로 문자를 입력하면 string형으로 저장할 겁니다.

**Comment by junhoprog** [comment]
var 타입을 사용해도 onChanged위젯 이후에 변수가 들어갈 땐 타입 상관없이 안되고 있습니다. 그래서 변수 저장방식을 바꿔서 해결하려고 합니다
