### ISSUE TITLE
운동 추천 기능 외 추가 기능 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#14]
사용자의 입장에서 운동도 중요하지만, 운동에 사용되는 물품과 영양제에 대한 정보를 필요로 할 수 있습니다.
사용자의 불편함을 덜기 위해서 추천운동 뿐만 아니라, 다른 상품들을 추천하는 기능을 추가하는 건 어떨까요?

**Comment by junhoprog** [comment]
좋은 생각인거 같습니다. 부족한 부위를 설명하는 과정에서 유용한 정보를 추가해서 추천한다면 더 좋을 것 같습니다.

**Comment by JungHyeono** [comment]
영양제 선호순위를 외부에서 가져와 활용하는것도 나쁘진 않을거 같습니다. 식단관리도 생각해보면 좋을거 같습니다.
