### ISSUE TITLE
사용자의 동기 부여를 위한 출석체크 기능 추가 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#15]
사용자가 앱을 사용하면서 효과를 얻기 위해서는 사용자의 동기부여가 중요하다는 생각이 듭니다.
동기부여를 하기 위해서 저는 출석체크 기능을 추가하는 것을 고려하고 있는데 여러분 생각은 어떠신가요?
출석체크가 아니더라도 동기부여를 할 수 있는 방법이 생각나시면 써주세요.

**Comment by junhoprog** [comment]
동기부여하는 것도 중요하지만 저희 앱의 취지가 추천앱이기 때문에 성격에 맞지 않을 수 있다 생각합니다.

**Comment by JungHyeono** [comment]
출석체크도 좋은 방안 같습니다. 다른 방안으로는 사용자가 자신의 몸이 변화하고 있는걸 시각적으로 표현해주는 것도 좋을거 같습니다.
