### ISSUE TITLE
세부적인 근육에 무지한 사용자를 위한 편의 기능 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#16]
세부적인 근육에 대한 정보를 알고 있으면, 그 부위에 대해 더 효과적으로 운동을 할 수 있다는 생각을 합니다.
사용자가 만약 근육에 대한 정보를 모를 경우, 근육에 대한 이미지와 설명을 추가하는 것은 어떨까요?

**Comment by junhoprog** [comment]
저도 제대로 운동을 배우게 된다면 이런 세세한 부위별 정보와 설명은 필요하다 생각합니다 좋은 생각인것 같습니다.

**Comment by JungHyeono** [comment]
근육에 대한 이미지, 설명도 좋지만 그 근육을 키운다면 실제론 어떻게 보이는지도 예시를 보여주는것도 좋을거 같습니다.
