### ISSUE TITLE
헬스장을 다니지 않는 사용자를 위한 운동 재분류 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#19]
헬스장을 다니지 않는 사용자들은 운동에 제약이 있을 수 있습니다. 예) 기구를 사용하는 운동
이러한 사용자들을 위해서 
1.기구를 사용하는 운동과 
2. 맨몸운동으로 나눠서 추천하는 방법을 생각해 보았습니다. 여러분의 생각은 어떠신가요?

**Comment by junhoprog** [comment]
제 생각은 등록페이지에서 애초에 사용자의 운동취향을 고려해서 선택하게 만들고 이에 맞게 추천하는식도 괜찮을거 같다 생각이 듭니다.

**Comment by JungHyeono** [comment]
아직 코로나 사회이기 때문에 헬스장을 가지 않는 사람을 고려해서 맨몸운동도 추가하는 방법이 좋을거 같습니다.
