### ISSUE TITLE
프로젝트 구현

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#2]
이번 프로젝트 구현시 어떤 언어로 웹또는 앱을 만들지 의견을 말해주세요!

**Comment by juhojang** [comment]
다양한 os에서 실행이 가능한 웹 프로그래밍이 좋을 거 같아. 비교적 난이도가 쉬운 html을 이용하여 작성하는게 어떨까?

**Comment by junhoprog** [comment]
html도 좋지만, 저희의 공통 언어가 c또는 c++이기 때문에  웹또는 앱을 만들게 되었을 때 다시 배워야 한다면, 전 새로운 언어를 배워 앱을 만들어보고 싶습니다. 그 중에서 dart언어를 활용한 flutter를 다같이 배워 만들어보면 좋을 것 같습니다.

**Comment by JungHyeono** [comment]
나도 C, C++으로 하고싶은데 우리가 만들어야 하는 웹이나 앱은 준호가 말한 플라터를 이용하는게 나을거같아
