### ISSUE TITLE
세부근육에 맞는 운동법 조사

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#21]
저희 앱의 취지는 세부근육에 대한 자세한 운동법을 사용자에게 가르쳐주는 것입니다.
근육의 개수가 많은 만큼 그에 따른 운동법의 개수가 많습니다. 파트를 분배하여 조사를 더 열심히 해야될 것 같습니다.
제가 근육을 분류해보았는데 다음과 같습니다.

1.팔근육
이두근육
삼두근육
전완근

2. 다리근육
대퇴근
대퇴이두근
대둔근
비복근

3. 몸통근육
대흉근
복근
승모근
삼각근
광배근

저희가 조사할 운동법은 강도에 따른 근육운동법입니다.
각자 파트를 나누어서 조사를 하는 것이 부담이 적을 것 같습니다.

1. 각자 파트를 나누고
2. 파트에 대해 조사를 완료하면 운동법을 설명하는 유튜브 동영상 링크를 공유합시다.

**Comment by junhoprog** [comment]
네 저는 몸통근육파트를 맡겠습니다. 맨몸운동과 기구를 사용하는 운동 두 분류 모두 우선 조사해서 공유하겠습니다.

**Comment by juhojang** [comment]
저는 팔근육 파트 맡겠습니다.

**Comment by JungHyeono** [comment]
그럼 저는 남는 파트인 다리파트쪽을 맡겠습니다.
