### ISSUE TITLE
사용자의 정보 추출 함수와 정보 분석 함수의 뼈대 리뷰 요청

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#22]
제가 간단하게 생각해본 뼈대는 다음과 같습니다.

추출 함수
{

라디오 위젯을 통해 성별 입력받기
if 남자 sex=0;
elif 여자 sex=2;

TextField 위젯을 통해 몸무게, 체지방량, (양팔, 양다리, 몸통 근육백분율) 입력받기

List<double> userInfo=[]; (리스트를 사용할지 딕셔너리를 사용할지 고민입니다. 여러분의 생각을 남겨주세요.)
list.append('키 정보')
list.append('몸무게 정보')
list.append('체지방 정보')
list.append('양팔, 양다리, 몸통 근육백분율 정보')

}

정보 분석 함수(남자버전)
{
/*남자의 정보를 기반으로 한 분석함수*/
userinfo[0](키)와 userinfo[1](몸무게)를 사용하여  BMI지수를 얻을 수 있음

userinfo[2]를 통해 사용자가 비만형인지 아닌지 판단 가능

userinfo[3]~...는 사용자가 골격근량이 평균인지 아닌지 판단 가능

}

정보 분석 함수(여자버전)
{
/*여자의 정보를 기반으로 한 분석함수*/

userinfo[0](키)와 userinfo[1](몸무게)를 사용하여  BMI지수를 얻을 수 있음

userinfo[2]를 통해 사용자가 비만형인지 아닌지 판단 가능

userinfo[3]~...는 사용자가 골격근량이 평균인지 아닌지 판단 가능

}

여기서 더 수정할 사항이 있다면 코멘트 남겨주세요.

**Comment by junhoprog** [comment]
저는 딕셔너리사용하는것이 데이터관리에 있어서 더 용이할 것 같습니다.
이외에 판단할 때 사용자로부터 얻은 이상적인 몸을 사용자와 같은 조건으로 먼저 분석해서 판단한다면 좋을거같습니다.

**Comment by juhojang** [comment]
네 참고하겠습니다
