### ISSUE TITLE
로그인 시스템 추가 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#23]
제가 전부터 생각하고 있었던 주제입니다.
저는 로그인 시스템을 추가하는게 좋다고 생각합니다.
이유는 다음과 같습니다.
1. 로그인을 함으로써 사용자의 정보 보안 보장
2. 사용자에게 개인화된 서비스 제공(사용자에게 더 잘 맞는 서비스 제공)

하지만 생각해본 단점도 있습니다.
1. 접근성 제한(계정을 만드는 것이 여러가지 이유로 꺼려짐) [ex)보안성이 보장되있나? 귀찮다]

여러분의 생각은 어떠신가요?

**Comment by junhoprog** [comment]
전 사실 로그인시스템에 대해 비우호적인 입장입니다. 저희 앱은 추천만 해주는 앱이기 때문에 자신의 체형을 알고 추천 받는 것 외에 사용자가 할 수 있는 기능이 없기때문에 굳이 필요할까라는 생각이 듭니다.

**Comment by JungHyeono** [comment]
로그인 시스템을 추가한다면 로그인 하기를 꺼리는 사람을 위한 게스트 로그인도 만들면 좋겠다고 생각합니다.
