### ISSUE TITLE
출석체크 기능 구현 관련 도움 요청

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#28]
제가 출석체크를 구현하려는데, 리스트에 날짜를 저장한 다음 set타입으로 변환하여 갯수를 세는 방법으로 1~10까지는 헬린이 같은 애칭을 붙이는 방법을 생각하고 있습니다.
 근데 고민 중 하나는 앱을 끄고 다시 킬 때, 값을 유지할 수 있는 방법을 모르겠습니다. 아시는 분은 코멘트 달아주세요,

**Comment by junhoprog** [comment]
shared preference API를 사용하면 될 것 같습니다.
키-값 쌍을 읽고 쓸 수 있는 간단한 메서드를 제공해서 값을 저장하고 검색할 때 좋을 것 같습니다.
