### ISSUE TITLE
상품추천을 위한 쿠팡 크롤링 기능 추가 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#29]
상품 리스트를 꺼내오기 위해서 쿠팡을 크롤링할려고 하는데 여러분 생각은 어떠신가요?
쿠팡 robots.txt는 다음과 같습니다.

User-agent: *
Disallow: /

User-agent: Googlebot
Crawl-delay: 1
Allow: /vp/products/
Allow: /vm/products/
Allow: /vr/products/
Disallow: /*.css$
Disallow: /*.js$

User-agent: Googlebot-image
Crawl-delay: 1
Allow: /vp/products/
Allow: /vm/products/
Allow: /vr/products/
Disallow: /*.css$
Disallow: /*.js$

User-agent: NaverBot
Crawl-delay: 1
Disallow: /*.gif$
Disallow: /*.jpg$
Disallow: /*.css$
Disallow: /*.js$
Disallow: /np/etc/trustPartners

User-agent: Yeti
Crawl-delay: 1
Disallow: /*.gif$
Disallow: /*.jpg$
Disallow: /*.css$
Disallow: /*.js$
Disallow: /np/etc/trustPartners

저희는 이윤추구를 하지 않기 떼문에 개발목적으로 사용가능할 것 같습니다.
쿠팡 말고 다른 크롤링하기 좋은 웹사이트 있음 코멘트 남겨주세요.

**Comment by junhoprog** [comment]
운동기구또는 용품은 가격 비교에 쉬운 쿠팡이 가장 좋을거 같습니다.

**Comment by JungHyeono** [comment]
운동기구나 영양제 같은건 저희가 조사해 추천하는거니 접근하기 쉬운 쿠팡이 제일 나을거같습니다.
