### ISSUE TITLE
프로젝트 역할 배분

### ISSUE THREAD

**Issue by JungHyeono** [JungHyeono/OSS-Project#3]
**필요한 역할**
- FrontEnd -1명
- BackEnd -2명

이렇게 두 개 정하면 될거같고 모델링 같은경우엔 다같이 구상해서 하는게 나을거 같습니다.
혹시 원하는 역할 있으시면 말해주시고 겹치는거 있으면 조율해서 나눠야 할 것 같습니다.

**Comment by JungHyeono** [comment]
저는 FrontEnd 같은 디자인은 해본적이 없어서 BackEnd를 하고싶습니당

**Comment by junhoprog** [comment]
저도 BackEnd하겠습니다. 만약에 파트에서 어려운 부분이 있으면 역할이 아니여도 도우면서 하면 될거 같습니다.

**Comment by juhojang** [comment]
모두 FrontEnd를 하지 않으니, 마침 디자인에 흥미가 있으므로 저는 ProntEnd 하겠습니다.
