### ISSUE TITLE
안드로이드 스튜디오와 핸드폰과 연결이 안되시는 분 필독!

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#31]
오늘 오전부터 안드로이드 스튜디오랑 핸드폰과의 연결을 시도하다가 번번히 실패하다가 드디어 알았습니다.
일단 이것들을 확인하세요
1. SDK 매니저가 google usb driver를 설치하였는지
2. 각자의 시스템의 환경변수가 한글이 포함되어있지 않은 sdk경로를 향하고 있는지

이 두개를 고치니까 해결되었습니다.

**Comment by junhoprog** [comment]
저도 이 부분에서 문제 있었는데 감사합니다
