### ISSUE TITLE
README.md 관련 논의

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#38]
README.md파일을 수정하려고 하는데
1.설치방법
2.의존성
3.사용(실행)방법
4.라이선스,연락처(이메일)
에 대한 내용을 작성해야합니다.
작성해야하는 내용이 있다면 말씀해주시기 바랍니다

**Comment by juhojang** [comment]
junhoprog님이 생성한 프로그램에 대한 정보를 채우는 공간이니 해당 프로그램 개발자가 스스로 작성하는게 맞다고 생각합니다. 저희는 junhoprog님의 프로그램에 대해 아는 것이 없으니까요.

**Comment by junhoprog** [comment]
저는 README.md파일을 한 사람이 만드는 건 줄 알고 통합해서 쓸 생각으로 말했던 거 였습니다! 우선 각자 쓰고 합치는 걸로 하는게 좋을 것 같네요
