### ISSUE TITLE
head detached관련 도움요청

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#39]
현재 진행중인 branch에서 main으로 merge를 하려고 할 때 head와 분리되어 pull과 merge둘 다 할 수 없는 상태가 되었습니다.
제가 많이 미흡한 부분이 있어서 이렇게 된 거 같은데 이 부분에 대해 해결 방안을 알려주시면 감사하겠습니다.

**Comment by juhojang** [comment]
1. 일단 JungHyeono/OSS-Project
의 main 브랜치는 merge 할때는 pull request를 이용해주시길 바랍니다.
2. <오류메세지를 올리시지 않아 문제를 추정하는 점 양해드립니다.>
main 브랜치로부터 현재브랜치에 pull을 못하는 경우는 아예 다른 히스토리를 가지고 있기 때문에 생기는 문제인 것 같습니다. 이때는 강제적으로 pull을 하는 명령어가 있습니다. (git pull origin <브랜치이름> --allow-unrelated-histories)
3. 그리고 인터넷에 찾아본 결과 'HEAD'란 특정 브랜치의 마지막 커밋에 대한 포인터를 의미한다고 합니다. 즉, junhoprog님이 가장 최근에 한 commit을 한 브랜치를 가리키게 될 것 입니다. 이 문제는 'HEAD'가 분리되어 생기는 문제는 아닌 것 같습니다.

**Comment by junhoprog** [comment]
해결완료했습니다 감사합니다.
