### ISSUE TITLE
앱개발전, 데이터또는 문제해결방안 구상

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#4]
저희가 우선 앱에서  짚고 넘어가야할 문제나 어떻게 처리할지 고민해야할 부분이 있습니다.

1. 사용자로부터 인바디 정보를 어떻게 불러올지
2. 분석한 데이터를 어떤 식으로 저장할지
3. 데이터를 토대로 어떤 운동을 무슨 기준으로 추천할 지

이외에 필요한 문제는 뒤에 말씀해주시고 위에 3가지 문제들은 어떻게 해결하면 좋을까요?

**Comment by juhojang** [comment]
1. 사용자가 직접 수기로 입력받는 방법이 있습니다. 사용자의 불편이 따르긴 하지만 가장 구현방법이 쉬울 것 같기 때문입니다.
2. 저는 구조체나 클래스를 이용하여 데이터를 체계적으로 저장하는 방법이 좋을 것 같습니다. 만일 클래스를 사용한다면 코드 재사용성이 높아지기 때문입니다.
3. 안에서 자체 저장해놓은 이상적인 몸의 비율과 사용자의 몸의 비율을 비교한 뒤, 전자의 몸에 못미치는 신체부위에 대한 강화운동을 추천하는게 좋을 것 같습니다.

**Comment by JungHyeono** [comment]
1. 인바디의 이미지를 스캔하거나 수기로 작성하는 방법이 좋을거 같습니다.
2. 데이터베이스나 구조체, 클래스를 이용한 서버가 아닌 사용자의 저장공간에 저장할 수 있게 만드는 것이 좋을거 같습니다.
3. 인바디를 먼저 측정하고 사용자가 원하는 슬림바디, 머슬바디 중에 하나 고르게 하고 체지방량, 골격근량에 맞는 운동위주로 추천을 하는게 좋을 것 같습니다.

**Comment by junhoprog** [comment]
결론적으로 
1. 사용자입력
3. 사용자에게 원하는 체형을 물어보고 이에 맞는 운동을 추천하는 식으로 하면 될거 같고

2번은 구현하면서 더 효율적인 기능으로 상의해보면 좋을거 같습니다.
