### ISSUE TITLE
크롤링에 문제가 발생했습니다.<파이썬과 플러터와의 연동 문제>

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#40]
제가 Feature_craw;ling을 만든 목적이 Feature_recommandShop의 추천 제품 리스트를 받아오기 위함이었습니다.
이 때, 제가 생각한 기본 전제는 플러터와 파이썬의 손쉬운 연동이었습니다.
막상 파이썬의 BeautifulSoup4를 이용하여 크롤링 프로그램을 만들었더니, 파이썬과의 연동에 문제가 생겼습니다.<두가지를 연동하는 것이 힘들다고 합니다.>

 그래서 제가 생각한  방법은 
1. 플러터의 _http 패키지를 이용하여 사이트의 json 형식의 파일을 불러오는 방법_인데, 이 방법은 쿠팡에서 개발자 옵션을 돌려봐도 원하는 데이터를 가진 json 형식의 파일을 찾을 수 없었습니다.
 
2. 플러터에서 _html 파서를 이용하여 정보를 추출하는 방법_을 생각해 보았는데, 아직 이러한 수행을 가능하게 하는 패키지를 발견하지 못하였습니다.

 혹시 html 파서를 이용하능하게 하는 플러터 패키지를 아신다면 코멘트 남겨주세요.
또는 쿠팡 페이지의 단백질 파우더의 제품, 가격, 이미지를 가지고 있는 json 형식의 파일을 발견하셨다면 코멘트 남겨주시기 바랍니다.

**Comment by junhoprog** [comment]
따로 json서버를 만들어서 크롤링한 정보를 넣고 쓰는 게 좋을 것 같습니다.
