### ISSUE TITLE
웹상에서 불러온 이미지가 안뜨는 경우 참고하세요.

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#41]
플러터가 웹에서 정보를 불러올 때, 플러터가 동작하고 있는 장치에 따라 renderer가 다르다고 합니다.

모바일(핸드폰) - html renderer
데스크탑 - canvas renderer

이때 canvas renderer는 웹상의 이미지를 로딩할 수 없는 것으로 보입니다. 따라서 크롭(웹)으로 테스트하시는 분은 canvas renderer를 쓰는게 아닌 html renderer로 쓰셔야 이미지가 보일 겁니다.

해결방법(html renderer을 쓰는 방법)은
1. 터미널에서 직접 flutter run -d chrome --web-renderer html 입력
2. main.dart 항목을 클릭하면 Edit Config
![화면 캡처 2022-05-12 190413](https://user-images.githubusercontent.com/55169382/168046352-3cbddec6-f104-4e4a-9185-f6cfd0cdfbd3.png)
![화면 캡처 2022-05-12 190351](https://user-images.githubusercontent.com/55169382/168046370-9692c265-d534-458e-9aa0-5c2a52d64f9a.png)

urations가 나오는데 Additional run args에 --web-renderer html 입력후 apply ok 버튼 누르기

**Comment by junhoprog** [comment]
참고했습니다 감사합니다.
