### ISSUE TITLE
Navigator Widget 데이터 전달시 의문

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#42]
Navigator 위젯을 사용하여 페이지를 옮길 수 있는데 이 때 등록 페이지에서 받은 데이터를 추천 페이지로 옮겨야 하는데 저희 시스템이 메인 페이지에서 등록 페이지로 가서 데이터를 받고 메인 페이지에서 다시 추천 페이지로 이동하는 식으로 알고 있습니다. 그러면 등록 페이지에서 메인, 추천 페이지 모두로 데이터를 받게 해야 할까요??

**Comment by juhojang** [comment]
추천 페이지에서 사용자의 데이터를 가지고 사용자에게 운동을 추천하는 것이니 추천 페이지만 받게 하면 될 거 같습니다.
 이 때, 추천 페이지가 받는 데이터가  raw 데이터가 아니었으면 좋겠습니다. 사용자 데이터 분석 함수로 정제된 데이터를 추천페이지로 보내는 것이 더 깔끔하다고 생각합니다.
 등록페이지에서 사용자 데이터 분석 함수를 삽입하여 데이터를 정제시킨 다음, 정제된 데이터를 추천페이지로 보내는 것이 좋을 것 같습니다.
