### ISSUE TITLE
현재 진행 상황

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#45]
현재 각자의 진행 상황과 이후에 더 필요할 것 같은 부분에 대해 의논해봅시다.

저같은 경우 메인 페이지와 등록 페이지 세팅은 완료한 상태입니다. 등록 페이지 같은 경우 현호님께서 사용자 분석 함수를 만든 후에 고민해봐야 할 것 같고, 두 페이지 모두 디자인을 더 신경써 보겠습니다.
만약에 주호님과 합치게 되었을 때 필요한 기능이나 제게 추가할 만한 요소가 있다면 말씀해주시면 감사하겠습니다.

**Comment by juhojang** [comment]
메인 페이지에서 출석체크 페이지로 가는 버튼을 더 추가해 주셨으면 합니다.

**Comment by junhoprog** [comment]
추가 완료하였습니다!
