### ISSUE TITLE
추적되지 않은 파일으로 인한 branch변경 불가문제

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#46]
현재 제가 한 프로젝트에서 2개의 브랜치를 같이 진행하고 있는데 전까진 괜찮았는데 갑자기 추적되지 않은 파일이 있다는 오류가 나타나고 있습니다. 확인해보니 각각의 다트파일이 영향을 주고 있어서 그런거 같은데 추적되지 않은 파일을 추가하지 않고 오류를 해결하는 방법을 알고계신분은 알려주시면 감사하겠습니다.
오류내용은 다음과 같습니다. 

error: The following untracked working tree files would be overwritten by checkout:

**Comment by juhojang** [comment]
git stash 명령어를 사용하십시오.

**Comment by junhoprog** [comment]
해결 완료했습니다 감사합니다.
