### ISSUE TITLE
앱의 구조 재구상

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#47]
현재 여러분들이 만들고 계신 페이지와 기능들을 어떤 구조로 앱을 구상할지 얘기해봐야 할 것 같습니다.

주호님께서는 출석 체크, 로그인, 추천 페이지를 맡고 계신대, 저의 메인 페이지와 어떤 식으로 연결할 지 같이 논의해봅시다.

**Comment by juhojang** [comment]
일단 로그인 페이지는 사용자의 접근성을 위해서 안 넣는게 좋을 것 같습니다.

**Comment by junhoprog** [comment]
네 로그 인페이지를 쓰게 된다면 따로 데이터베이스를 관리하는데 있어서 어려움이 있을 수 있어 저도 좋다 생각합니다. 
저희는 안넣는 걸로 합의하도록 하겠습니다.
