### ISSUE TITLE
사용자 분석 함수 데이터관련 질문

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#49]
등록 페이지에서 받은 데이터를 정제하여 나온 결과물을 추천 페이지로 옮기는 작업을 하게 되면 추천 페이지로 사용자의 이상적인 체형과 분석한 사용자의 몸 상태 결과를 모두 보내는 건지 아니면 결과물만 인지 궁금해서 질문드립니다!

**Comment by juhojang** [comment]
추천페이지로 사용자의 몸상태 결과와 사용자가 원하는 이상적 체형 두개를 보내면 될 것 같습니다.

**Comment by junhoprog** [comment]
사용자의 이상향 체형을 등록 페이지에서 쓸모 있는 데이터로 정제를 해서 1개의 데이터로만 보내도록 하겠습니다.
원하시는 방향으로 갈 수 있도록 만들어 보겠습니다.
