### ISSUE TITLE
사용자의 인바디 정보를 입력받는 방식

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#5]
사용자의 인바디 정보를 입력받는 방식을 
1. 인바디 결과지에 있는 qr코드를 통해 입력받을지 
2. 아니면 사용자가 직접 입력할지
두가지 방식을 생각하고 있습니다.
두 가지 방식이 아니더라도 생각나는 방식에 대해 코멘트 남겨주세요.

**Comment by junhoprog** [comment]
2번 방식이 나을 거 같습니다. 1번은 인바디 검사지마다 없는 것도 있기 때문에 사용자에겐 번거롭더라도 구현하는덴 어렵지 않을 거 같습니다.

**Comment by JungHyeono** [comment]
저도 2번이 괜찮다고 생각합니다. QR코드로 데이터를 받을 시 인바디케어 사이트에 들어가 회원가입을 하고 정보를 불러와야 하기때문에 차질이 생길 거 같습니다. 다른 방법으로는 사진을 스캔해서 이미지를 데이터화 하는 방법도 있긴 한데 Flutter에서 구현은 기대하기 힘들거 같습니다.
