### ISSUE TITLE
package 사용시 유의사항

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#57]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/87304269/170173737-91b810a9-722c-4a3d-baa3-ca2ea143c4ee.png">
위의 그림과 같이 오류가 발생한다면
<img width="380" alt="image" src="https://user-images.githubusercontent.com/87304269/170173872-414f246e-d2fa-402d-a41b-b4a9f7d4bc7f.png">
Additional run args창에 --no-sound-null-safety를 추가하시면 해결되실겁니다!

**Comment by juhojang** [comment]
네 참고하겠습니다
