### ISSUE TITLE
인바디 추천에 필요한 데이터 종류

### ISSUE THREAD

**Issue by JungHyeono** [JungHyeono/OSS-Project#6]
### 필요한 데이터
- 키, 몸무게
- 성별
- 체지방량
- 골격근량(부위별 골격근량)
### 목적
-  체지방량과 골격근량을 대조해 사용자가 원하는 바디의 알맞는 운동 추천.

**Comment by JungHyeono** [comment]
**더 필요한 데이터나 추가사항 있으시면 의견 부탁드립니다!!**

**Comment by junhoprog** [comment]
사용자마다 원하는 몸이 다르기 때문에 통상적인 기준이 필요할 거 같습니다. 그래서 저희가 사용자에게 체형 선택지를 주고원하는 데이터를 얻는 방식도 좋을거같습니다.
