### ISSUE TITLE
데이터중, 버그 발생

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#61]
데이터 중에서 유튜브 링크가 뜨지 않는 버그를 발견했습니다.
여러 데이터들을 적용해본 결과 '보통'인 데이터 페이지에서 나오는 문제인것 같습니다.
제 등록 페이지에서 추천 페이지로 보낼 때의 데이터를 고쳐서 맞추겠습니다.

**Comment by junhoprog** [comment]
해결 완료 하였습니다.

**Comment by juhojang** [comment]
준호님의 코드에선 '보통'이라고 명칭하였고, 제 파트에선 '중간'이라고 칭했기 때문에 생긴 오류입니다.
