### ISSUE TITLE
이미지 깨짐현상

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#62]
현재 제 Emulator에서 운동추천 페이지에서 쓰이는 이미지들이 깨지는 현상이 발생했었습니다.
각자 휴대폰으로 확인 한번씩 하시구 수정 필요하다면 말씀 부탁 드립니다.

**Comment by junhoprog** [comment]
![image](https://user-images.githubusercontent.com/87304269/170987815-e7e5c00f-0a63-45fb-ac9a-1d222728a5a1.png)

**Comment by junhoprog** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/87304269/170988177-0dfbc860-f1c4-4105-89c9-8ab6150f3d23.png">

**Comment by junhoprog** [comment]
모바일과 웹간의 주소차이로 인한  load할 수 없는 부분이 있었나봅니다.
assets/(이미지이름).jpg형태로 해줘서 해결완료했습니다.

**Comment by juhojang** [comment]
제가 이 파트 담당자인데,
저 이미지를 불러올 때 웹에서 불러온 것이 아닙니다. 
프로젝트 파일 안에 내장된 이미지를 불러온 것인데, 웹의 주소차이로 인한 문제가 무엇인가요?
