### ISSUE TITLE
링크 이동 불가현상 발생

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#64]
저희앱에서 추천페이지마다 유튜브 바로가기(링크이동)이 필요합니다.
그런데 onTap위젯이 웹사이트에선 잘되는데 모바일에선 링크이동은 없고 무 반응 상태입니다. 
이에 대해 해결방법 알고있다면 공유부탁드립니다.

**Comment by junhoprog** [comment]
https:/~링크형태인 url이 앱으로 실행시 http로 바뀌면서 링크가 맞지않아 load가 되지않는 것이였습니다.
그래서 https://dev-yakuza.posstree.com/ko/flutter/url_launcher/external_link/
를 참고하여 문제를 해결하였고 원래 있던 조건문의 형태를 바꿔서 해결했습니다.

**Comment by juhojang** [comment]
준호님이 해결방법을 제시한 링크는 외부 브라우저를 통해 링크를 열 수 있는 방법을 설명한 사이트입니다.
문제 원인은 다음과 같습니다.
핸드폰의 OS인 안드로이드가 9.0 이후 버전으로 업데이트 되면서 HTTP와 같은 Url스키마에 대한 접근 제한이 생겼습니다.(보안상 문제, https는 통신에 대한 암호화 기능을 제공하기 때문, HTTP는 그러지 않음)
따라서 이를 해결하기 위해 AndroidManifest의 <application 속성에 android:usesCleartextTraffic를 true로 바꿨습니다.
이는 모든 HTTP Url에 대한 접근을 허용하겠다는 뜻으로, HTTP를 HTTPS로 전환하는 것이 아닙니다.
