### ISSUE TITLE
기말 발표자료 구성상의

### ISSUE THREAD

**Issue by junhoprog** [JungHyeono/OSS-Project#67]
우선 저희가 발표 자료를 만들어야 하는데 구조를 먼저 짜야 할 것 같습니다.
이번 발표에서 필요한 것은 다음과 같습니다.

-Problem
-차별성
-Solution
-결과물
-한계점
-개선방향

어떤 식으로 만들지 같이 상의해봅시다.

**Comment by juhojang** [comment]
우선 한계점은 프로젝트 담당자 모두 Mac OS를 사용하는 사람이 없어 ios용 앱을 빌드하지 못했다는 것입니다.
