### ISSUE TITLE
프로젝트 역할 재배분

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#7]
플러터로 앱을 만들 때, FrontEnd와 BackEnd의 역할 배분이 모호하여 다시 역할을 재배분 하려고 합니다.
제가 생각한 역할 배분은 이렇습니다.
1. 시작 페이지 및 사용자의 데이터를 입력받는 페이지 만들기
2.  사용자의 데이터를 분석하는 함수 만들기
3.  분석한 데이터를 토대로 운동을 추천하는 페이지 만들기

이렇게 크게 세 가지가 있다고 생각합니다.
여러분이 원하는 역할을 선택해 주세요. 만약 세부적으로 수정 사항이 있다면 코멘트 남겨주세요.

**Comment by juhojang** [comment]
저는 3번을 만들고 싶습니다. 사용자에게 친근한 위젯과
위젯과 웹 간의 이동을 구현하는데 자신이 있기 때문입니다.

**Comment by junhoprog** [comment]
전 지금 진행중인 시작 페이지를 만들고 필요하다면 다른 기능도 추가하겠습니다.

**Comment by JungHyeono** [comment]
저는 그럼 2. 사용자의 데이터를 분석하는 함수를 담당하도록 하겠습니다.
