### ISSUE TITLE
인앱브라우저, 외부브라우저 둘 중 무엇을 사용할 지에 대한 논의

### ISSUE THREAD

**Issue by juhojang** [JungHyeono/OSS-Project#9]
운동추천을 할 때, 저희 앱은 링크를 통해 유튜브 동영상을 사용자에게 띄어줍니다.
이 때, 인앱브라우저를 쓸지, 외부브라우저를 쓸지 논의해봅시다.

**Comment by junhoprog** [comment]
전 편의상 외부브라우저를 사용하는게 나을거 같습니다.

**Comment by JungHyeono** [comment]
인앱브라우저는 접근성이나 편리성이 떨어져 외부 브라우저를 쓰는게 괜찮을거 같습니다.

**Comment by juhojang** [comment]
제가 찾아본 결과 인앱브라우저가 사용상 편의가 좋고, 앱에 대한 권한이 인앱브라우저에서 발휘될 수 있기 때문에 인앱브라우저가 좋은 것 같습니다.
